### ISSUE TITLE
Fix firebase security rules for private data

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/vox#15]
Currently, anyone logged in can change anything; auth rules should be restricted so users can only change their own votes.

Ref #12

**Comment by simoneduca** [comment]
Change what exactly? I have noticed your votes, but I couldn't overwrite/remove them.

**Comment by rogerhutchings** [comment]
A bug in the code could overwrite votes, however, as it only checks for _someone_ to be logged in, not the owner of the vote. So that should be changed in https://console.firebase.google.com/project/project-6243802502502885389/database/rules so that only the user can edit their own votes

**Comment by simoneduca** [comment]
I'm trying to change the rules according to the [FB docs (user tab)](https://firebase.google.com/docs/database/security/quickstart#sample-rules).
I've tried this 

```
{
  "rules": {
    "issues": {
      "$uid": {
        ".read": "true",
        ".write": "$uid === auth.uid"
      }
    },
    "users": {
      "$uid": {
        ".read": "auth != null",
        ".write": "$uid === auth.uid"
      }
    }
  }
}
```

But now I get permission denied every time I vote. Any thoughts?

**Comment by rogerhutchings** [comment]
Well, issues isn't keyed by `auth.uid` for one thing

**Comment by simoneduca** [comment]
@rogerhutchings how does this look? I changed the rules in the console to the following and I think it's correct now.

```
{
  "rules": {
    "issues": {
      ".read": "true",
    	".write": "auth != null"
    },
    "users": {
      "$uid": {
        ".read": "auth != null",
        ".write": "auth != null",
      }
    }
  }
}
```

**Comment by rogerhutchings** [comment]
A bug could still cause a user to overwrite another user's data, as anyone can read / write to any user as long as they're logged in. The rules were correct before, but I think the problem lies in that nodes under `users` are keyed by GitHub ID, not Firebase uid. So if you use that...

```
{
  "rules": {
    "issues": {
      ".read": "true",
      ".write": "auth != null"
    },
    "users": {
      "$uid": {
        ".read": "$uid === auth.uid",
        ".write": "$uid === auth.uid"
      }
    }
  }
}
```

...should work

**Comment by simoneduca** [comment]
Ah that makes sense thanks!
Just made a PR.
